"""add product reviews

Revision ID: 5387a5f93fd2
Revises: 3153c4f2f879
Create Date: 2026-07-27 00:11:53.444118

"""
from alembic import op
import sqlalchemy as sa
import models.types


# revision identifiers, used by Alembic.
revision = '5387a5f93fd2'
down_revision = '3153c4f2f879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews',
    sa.Column('id', models.types.GUID(), nullable=False),
    sa.Column('product_id', models.types.GUID(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_reviews')
    # ### end Alembic commands ###
