"""add coming soon fields and product notifications

Revision ID: d342ed33e4c3
Revises: 5387a5f93fd2
Create Date: 2026-08-09 00:39:53.956809

"""
from alembic import op
import sqlalchemy as sa
import models.types
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd342ed33e4c3'
down_revision = '5387a5f93fd2'
branch_labels = None
depends_on = None


def upgrade():
    # Made idempotent: each step checks if the table/column already exists
    # before acting.  This is necessary because SQLite doesn't support
    # transactional DDL — a crash mid-migration leaves partial changes
    # behind, and a naive re-run hits "already exists" errors.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # --- Step 1: product_notifications table ---
    if 'product_notifications' not in existing_tables:
        op.create_table('product_notifications',
            sa.Column('id', models.types.GUID(), nullable=False),
            sa.Column('product_id', models.types.GUID(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('product_id', 'email', name='uq_product_notification_email')
        )
    # Add index if it doesn't exist yet
    pn_indexes = [i['name'] for i in inspector.get_indexes('product_notifications')] if 'product_notifications' in inspector.get_table_names() else []
    if 'ix_product_notifications_email' not in pn_indexes:
        with op.batch_alter_table('product_notifications', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_product_notifications_email'), ['email'], unique=False)

    # --- Step 2: newsletter_subscribers.source column ---
    ns_columns = [c['name'] for c in inspector.get_columns('newsletter_subscribers')]
    if 'source' not in ns_columns:
        with op.batch_alter_table('newsletter_subscribers', schema=None) as batch_op:
            batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))

    # --- Step 3: products.is_coming_soon + release_date columns, file_path nullable ---
    # Drop any leftover temp table from a previous crashed attempt
    if '_alembic_tmp_products' in inspector.get_table_names():
        op.execute(sa.text('DROP TABLE _alembic_tmp_products'))

    products_columns = [c['name'] for c in inspector.get_columns('products')]
    needs_batch = False
    if 'is_coming_soon' not in products_columns or 'release_date' not in products_columns:
        needs_batch = True
    if needs_batch:
        with op.batch_alter_table('products', schema=None) as batch_op:
            if 'is_coming_soon' not in products_columns:
                batch_op.add_column(sa.Column('is_coming_soon', sa.Boolean(), server_default='0', nullable=False))
            if 'release_date' not in products_columns:
                batch_op.add_column(sa.Column('release_date', sa.String(length=50), nullable=True))
            batch_op.alter_column('file_path',
                   existing_type=mysql.VARCHAR(length=500),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('release_date')
        batch_op.drop_column('is_coming_soon')

    with op.batch_alter_table('newsletter_subscribers', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('product_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_notifications_email'))

    op.drop_table('product_notifications')
    # ### end Alembic commands ###
